import os
os.system("cat /etc/passwd")
raise RuntimeError('Purpose Fail')
